---
# call role db

- name: deploy Database
  hosts: $group
  vars: 
    group: db
  vars_files:
    - secret_passwords.yml
  roles:
    - db
  sudo: yes

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
