---
# This playbook deploys the whole application stack in this site.  


- name: apply common configuration to all nodes
  hosts: all
  user: root
  roles:
    - common

- include: mysql.yml
  when: mediatum_db_type == "mysql"

- include: mediatum.yml

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
