---
##### debian specific tasks which are run as sudo root
### install
- name: install build essentials
  apt: pkg=build-essential state=present

- name: install python system packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-dev
    - python-imaging
    - python-ldap
    - python-pip
    - python-pypdf

- name: install python package for mysql
  apt: pkg=python-mysqldb state=present

- name: install ffmpeg
  apt: pkg=ffmpeg state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 12
        or ansible_distribution == "Debian" and ansible_distribution_major_version|int < 7
  register: ffmpeg

- name: install libav-tools
  apt: pkg=libav-tools state=present
  when: ffmpeg|skipped


- name: install some media libs / tools
  apt: pkg={{ item }} state=present
  with_items:
    - xpdf
    - libjpeg8-dev
    - libart-2.0-dev
    - libgif-dev
    - imagemagick
    - graphviz

- name: install libpcre
  apt: pkg={{ item }} state=present
  with_items:
    - libpcre3
    - libpcre3-dev

- name: install libssl-dev
  apt: pkg=libssl-dev state=present


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
