---
- include: mediatum.root.yml
  sudo_user: root

- include: nginx.yml
  sudo_user: "{{ mediatum_admin_user }}"

- include: mediatum.yml
  sudo_user: "{{ mediatum_admin_user }}"
  notify: restart mediaTUM
  tags: mt

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
