---
# install mediatum (tasks executed as root)

- name: install build essentials
  apt: pkg=build-essential state=present

- name: install python system packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-dev
    - python-reportlab
    - python-imaging
    - python-ldap
    - python-pypdf
  sudo: yes

- name: install python package for mysql
  apt: pkg=python-mysqldb state=present
  when: mediatum_db_type == "mysql"

- name: install python package for sqlite
  apt: pkg=python-sqlite state=present
  when: mediatum_db_type == "sqlite"

- name: install pip
  apt: pkg=python-pip state=present
  sudo: yes

- name: install python packages via pip
  pip: name={{ item }} state=present
  with_items:
    - python-Levenshtein
    - pymarc
    - mollyZ3950
  sudo: yes


- name: install other media libs / tools
  apt: pkg={{ item }} state=present
  with_items:
    - xpdf
    - libjpeg8-dev
    - libart-2.0-dev
    - libgif-dev
    - imagemagick
  sudo: yes

- name: install ffmpeg
  apt: pkg=ffmpeg state=present

- name: install cvs
  apt: pkg=cvs state=present

- name: login to sourceforge CVS
  command: cvs -d:pserver:anonymous:@mediatum.cvs.sourceforge.net:/cvsroot/mediatum login

- name: get mediatum CVS
  command: chdir={{ mediatum_basedir }} cvs -z3 -d:pserver:anonymous@mediatum.cvs.sourceforge.net:/cvsroot/mediatum co -P mediatum

- name: make media dir
  file: path={{ mediatum_media_dir }} state=directory

- name: make logging dir
  file: path={{ mediatum_logdir }} state=directory

- name: make search dir
  file: path={{ mediatum_search_dir }} state=directory

- name: set mediatum_dir fact
  set_fact: mediatum_dir={{ mediatum_basedir }}/mediatum

- name: prepare mediaTUM config file
  template: src=mediatum.cfg.j2 dest={{ mediatum_dir }}/mediatum.cfg

- name: run checks
  command: chdir={{ mediatum_dir }} python bin/checkrequirements.py

#- name: kill running mediaTUM server
#  shell: chdir={{ mediatum_dir }} killall 'python start.py'
#  ignore_errors: yes

#- name: start mediaTUM server
#  shell: chdir={{ mediatum_dir }} python start.py &

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
